import { createHash } from "node:crypto";
import * as z from "zod/v4";
import {
  UNIVERSAL_AUTHORITY_RISKS,
  UNIVERSAL_BROKER_BUDGETS,
  UNIVERSAL_BROKER_VERSION,
  UNIVERSAL_ERROR_CODES,
  UNIVERSAL_TOOL_CONTRACTS,
  UNIVERSAL_TOOL_NAMES,
  UNIVERSAL_TOOL_OPERATIONS,
  universalRequestMetaSchema,
  universalResultEnvelopeSchema,
} from "./contracts.js";
import { BASE_BUILD_PROFILE_CONTRACT } from "./profile-contract.js";

export interface RuntimeContractSourceInput {
  authorityPolicySource: string;
  authorityPrincipalSource: string;
  authorityCoreSource: string;
  serverCanonicalizationSource: string;
  connectorAuthorityDescriptorSource: string;
  connectorActivationEvidenceSource: string;
  connectorActivationFinalizerSource: string;
  connectorStagingActivationContractSource: string;
  connectorRouteIdentitySource: string;
  resourceUriSource: string;
  unifiedConfigSource: string;
  unifiedConfigSchema: unknown;
}

export interface ComputedRuntimeContractIdentities {
  schemaGeneration: string;
  authorityContractGeneration: string;
}

/**
 * Compute the two public generations from the complete canonical source surfaces.
 * This runs only in generation/tests; the serving runtime imports the generated,
 * dependency-free constants from runtime-contract-identity.ts.
 */
export function computeRuntimeContractIdentities(
  sources: RuntimeContractSourceInput,
): ComputedRuntimeContractIdentities {
  const authorityContractGeneration = digest({
    version: "authority-contract-source-v1",
    risks: UNIVERSAL_AUTHORITY_RISKS,
    authorityPolicySourceSha256: sourceDigest(sources.authorityPolicySource),
    authorityPrincipalSourceSha256: sourceDigest(sources.authorityPrincipalSource),
    authorityCoreSourceSha256: sourceDigest(sources.authorityCoreSource),
    serverCanonicalizationSourceSha256: sourceDigest(sources.serverCanonicalizationSource),
    connectorAuthorityDescriptorSourceSha256: sourceDigest(sources.connectorAuthorityDescriptorSource),
    connectorActivationEvidenceSourceSha256: sourceDigest(sources.connectorActivationEvidenceSource),
    connectorActivationFinalizerSourceSha256: sourceDigest(sources.connectorActivationFinalizerSource),
    connectorStagingActivationContractSourceSha256: sourceDigest(
      sources.connectorStagingActivationContractSource,
    ),
    connectorRouteIdentitySourceSha256: sourceDigest(sources.connectorRouteIdentitySource),
  });
  const resultSchema = z.toJSONSchema(universalResultEnvelopeSchema, {
    target: "draft-07",
    io: "output",
    reused: "inline",
  });
  const schemaGeneration = digest({
    version: UNIVERSAL_BROKER_VERSION,
    productProfile: BASE_BUILD_PROFILE_CONTRACT.productProfile,
    supportedProfiles: BASE_BUILD_PROFILE_CONTRACT.supportedProfiles,
    supportedOperations: UNIVERSAL_TOOL_OPERATIONS,
    resourceUriVersion: BASE_BUILD_PROFILE_CONTRACT.resourceUriVersion,
    resourceUriGrammarSourceSha256: sourceDigest(sources.resourceUriSource),
    unifiedConfigSourceSha256: sourceDigest(sources.unifiedConfigSource),
    unifiedConfigSchema: sources.unifiedConfigSchema,
    commonRequestMetaSchema: z.toJSONSchema(universalRequestMetaSchema, {
      target: "draft-07",
      io: "input",
      reused: "inline",
    }),
    tools: UNIVERSAL_TOOL_NAMES.map((name) => {
      const contract = UNIVERSAL_TOOL_CONTRACTS[name];
      return {
        name,
        title: contract.title,
        description: contract.description,
        inputSchema: z.toJSONSchema(z.object(contract.inputSchema), {
          target: "draft-07",
          io: "input",
          reused: "inline",
        }),
        outputSchema: resultSchema,
        annotations: contract.annotations,
      };
    }),
    errors: UNIVERSAL_ERROR_CODES,
    budgets: UNIVERSAL_BROKER_BUDGETS,
    authorityContractGeneration,
  });
  return { schemaGeneration, authorityContractGeneration };
}

export function generatedRuntimeContractIdentitySource(
  identities: ComputedRuntimeContractIdentities,
): string {
  return [
    "/**",
    " * Generated by scripts/generate-universal-broker-v2-contracts.mjs.",
    " * Dependency-free so runtime and immutable-package verification share exact identities.",
    " */",
    `export const RUNTIME_SCHEMA_GENERATION = ${JSON.stringify(identities.schemaGeneration)};`,
    "",
    `export const RUNTIME_AUTHORITY_CONTRACT_GENERATION = ${JSON.stringify(identities.authorityContractGeneration)};`,
    "",
  ].join("\n");
}

function sourceDigest(value: string): string {
  const normalized = value.replaceAll("\r\n", "\n");
  return `sha256:${createHash("sha256").update(normalized).digest("hex")}`;
}

function digest(value: unknown): string {
  return `sha256:${createHash("sha256").update(canonicalJson(value)).digest("hex")}`;
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .filter(([, child]) => child !== undefined)
      .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)
      .map(([key, child]) => `${JSON.stringify(key)}:${canonicalJson(child)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value) ?? "null";
}
