/**
 * Generated by scripts/generate-universal-broker-v2-contracts.mjs.
 * Dependency-free so runtime and immutable-package verification share exact identities.
 */
export const RUNTIME_SCHEMA_GENERATION = "sha256:5e84c4d1a74d2662340f56a339a96f8378343af3d1294e7f61f4192d9b7daa06";

export const RUNTIME_AUTHORITY_CONTRACT_GENERATION = "sha256:d6dbf7aab20ee8bfe527d953f9296ed59c7821bd4f4d36cbefb69df225081b6f";
