/**
 * Generated by scripts/generate-universal-broker-v2-contracts.mjs.
 * Dependency-free so runtime and immutable-package verification share exact identities.
 */
export const RUNTIME_SCHEMA_GENERATION = "sha256:12d84724436231e4d3b7a64edfc01bd73fec4cf6bdc48289cb9f9f1a1eb5ccf5";

export const RUNTIME_AUTHORITY_CONTRACT_GENERATION = "sha256:6b9b4f43afc81081abf75a67c600ef8989d515f13b21d49ba5b8afcf102b5e1a";
