/**
 * Generated by scripts/generate-universal-broker-v2-contracts.mjs.
 * Dependency-free so runtime and immutable-package verification share exact identities.
 */
export const RUNTIME_SCHEMA_GENERATION = "sha256:9d2e836ffecafddceccf897053467229698b61e600c9aff9fbc49618c5c79dcb";

export const RUNTIME_AUTHORITY_CONTRACT_GENERATION = "sha256:21d2796d85cb14ede3c5968be38956fe157e4554559efa71a5438f2f79c719da";
